import * as functions from './modules/functions.js'

functions.isWebp()
functions.serachSelect()
functions.goodsTabs()
functions.mainSlider()
functions.mainMenu()
functions.modalCall()
functions.modalLogin()
functions.modalRegistration()
functions.modalForgot()
functions.modalProfile()
functions.modalProfileMobile()
functions.catalogMobile()
functions.moreMobile()
functions.maskPhoneNumber()
functions.validateModalRegistr()
functions.validateModalLogin()
functions.validateModalForgot()
functions.validateModalCall()
