import * as functions from './modules/functions.js';
import * as functions2 from './modules/functions2.js';
import * as maps from './modules/ymaps.js';

functions.isWebp();
functions.serachSelect();
functions.orderSelect();
functions.goodsTabs();
functions.tabsOrder();
functions.mainSlider();
functions.mainMenu();
functions.modalCall();
functions.modalLogin();
functions.modalRegistration();
functions.modalForgot();
functions.modalProfile();
functions.modalProfileMobile();
functions.catalogMobile();
functions.moreMobile();
functions.maskPhoneNumber();
functions.validateModalRegistr();
functions.validateModalLogin();
functions.validateModalForgot();
functions.validateModalCall();
functions.youtubeModal();
functions.youtubeSlider();
functions.sparesListSlider();
functions.catalogItemSlider();
functions.catalogItemTabsSlider();
functions.modalBuy();
functions.modalSort();
functions.modalFilter();
functions.filterRangeSlider();
functions.tabsCard();
functions.searchResult();
functions.cartClose();
functions.profileListClose();
functions.modalApplication();
functions.counterCatalogItem();
functions.ellipsisSimilar();
// functions.iframeMapStyles();

maps.ymapCentral();
maps.ymapShop();
maps.ymapDillers();
maps.ymapServices();

functions2.sparesExpand();
